def COLOR_MAP = [
    'SUCCESS': 'Good',
    'FAILURE': 'Danger',
]


pipeline {
    
	agent any
	
    environment {
        cluster = "czproprodcluster"
        service = "czproprodsvc"
        


    }
	
    stages{
        stage('Deploy to ECS Prod ') {
            steps {
                withAWS(credentials: 'awscred', region: 'ap-south-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }

    }
    post {
        always {
            echo "Slack Notification"
            slackSend(
                channel: '#devops-projects',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
            )

        }
    }

}
